### ISSUE TITLE
What is the purpose of code-style-guides?

### ISSUE THREAD

**Issue by samselikoff** [tedconf/code-style-guides#24]
I've been working off the assumption that the purpose of `code-style-guides` is to
- surface our team's best practices
- help our apps incorporate these best practices, making them look as if they're written by the same person

Joe made a comment in #19

> As a team, TED Tech has not yet established the problems we'd like to see addressed by TED's code style guides that are not yet addressed by Rubucop and other style guides & tools. Nor have we established any expectations about contributions to this guide.

which makes it clear that I have been working off a false assumption. I'd like us to try to establish these problems, so that we're all working to solve the same thing.

To my mind, some problems are
- By looking at some Ember code, I can tell whether it was written by Brenna, me, Ryan, or others (consultants et al)
- By looking at some CSS styles from different apps, I can tell whether they were written by me or Joe
- It is hard to discover our team's best practices

and so on. Basically, I find these large variations in code problematic. This worries me, because we've now all been hammering out code for years, and there's a lot of inconsistencies across our apps. We also have to bother each other a lot to ask questions that could be answered by a style guide, so I think this considerably slows us down. I am worried that by continuing to develop on our own, without shared resources beyond Rubocop/jshint/etc, we are creating a bigger mess that is going to get harder to clean up and slow us down even more in the future. I also think that an imperfect, even flawed styleguide that we all conform to would be an improvement over all of us sticking to our own coding styles. I think there should be a TED way to write JS, CSS, ruby etc., and I think all our apps should look like they are written in that style.

Okay, that's my take. Some questions for you all:
1. Do you agree that these are real and important problems?
2. If so, do you agree `code-style-guides` is the first and best way to solve them?
3. If not, what do you think the problems are that `code-style-guides` solves?

**Comment by brenna** [comment]
I agree that these are important concerns, and I will add a few additional issues I hope `code-style-guides` will address:

* better onboarding for new devs: less questions about "what's the right way to do this at TED?"
* similarly, reduce friction when someone wants to code in a language they don't normally write (eg. if i stepped into some rails code)
* even experienced devs will likely save some time if style decision overhead is removed
* allow us to be more productive with code reviews/PRs (i.e. critique based on style guide, not personal preference)
* build TED Tech's presence as a great engineering team

To Joe's question about what purpose they serve over linters, I imagine style guides as a super-set of what linters cover - linters won't cover the full spectrum of how we want to write our code (eg. Sass file structure), and where there is linter coverages, there's value in being able to read those rules in human-friendly language. I also imagine this could be a place where we state that we always use a linter - because right now that's not really a rule. 

All that being said, I agree that this initiative is bit disorganized as of now. What about electing a maintainer for each language? What about breaking languages out into separate repos to narrow our focus?

**Comment by samselikoff** [comment]
I like your thoughts Brenna. I want to think more about having a single
person be designated maintainer of each language, but initially this
strikes me as a very good idea. Joe for CSS, Ryan for Ember etc. (as a
thought experiment). These maintainers would obviously still listen to
input from the rest of the team (as is our culture), but ultimately when a
decision needs to be made, the maintainer would decide and we'd all be on
the same page.

I think if we had done something like this two years ago, it could have
been really good. We'd have our dozen or so apps right now looking much
more consistent, and as you say Brenna, a solid reference for us,
consultants etc.

**Comment by brenna** [comment]
Maybe this would make a good eng. meeting topic.  Decide on 1) a list of languages that need a guide 2) a maintainer for each. 

And yes, by maintainer I don't mean the person calling the shots, but someone who owns the guide to ensure it has momentum and is kept up to date/enforced via tooling etc.
