### ISSUE TITLE
meta-discussion: how to reach consensus on proposed style changes?

### ISSUE THREAD

**Issue by alexdean** [tedconf/code-style-guides#49]
what's a fair standard for evaluating whether or not to merge a given rubocop rule change?

  1. in general, i think it ought to be 'majority rules'
  1. but the existing/incumbent ruleset needs to get some deference. we need to avoid introducing code churn through changes in the style guide.

so i think the standard should vary depending on the kind of change proposed.

  1. relaxing an existing rule (which will cause no new violations) should only require a majority of favorable comments/votes, after allowing a reasonable amount of time for comments. maybe a week?
  1. adding/changing an existing rule which will likely cause lots of currently-ok code to suddenly be in violation needs to be held to a much higher standard.

@tedconf/backenders would appreciate feedback here. with some of the rubocop PRs I've suggested in the past, I haven't been sure what's a fair way to resolve differences of opinion.

**Comment by alexdean** [comment]
### organizational vs community

i think 'the community' is too amorphous of a thing to have a well-articulated opinion. i don't agree with the implicit asssertion that there is a single/common community solution. (i think it's incorrect to assume that rubocop's defaults are a de facto standard for ruby projects.)

i believe rubocop allows configuration precisely because there it is understood that there's no single right way to do everything. rubocop aims to include everything you could possibly want in a static code checker, and it's on users to decide what they do/don't want.

rails, for instance, uses [a very strictly limited configuration](https://github.com/rails/rails/blob/master/.rubocop.yml). i'd be much happier with that approach, and i regret not realizing that when i first proposed adopting a common rubocop config.

even [the ruby style guide](https://github.com/bbatsov/ruby-style-guide) doesn't include all the things that rubocop does. the 2 projects are semi-related, but one does not really enforce the other.

### bikeshedding

i agree with you on this. i've tried to restrain my PRs to only the things that really chafe me, and which consistently chafe over a significant amount of time. i don't want to endlessly argue minutiae, but i also can't say that i don't care about style. i do care about it, but i'm definitely aiming to only propose changes which really feel like they rise above the others.

and in the cases where i hear that y'all don't agree, that actually helps me make peace with whatever rule it was that i didn't like. knowing that i'm conforming to the opinions of people i respect, vs. conforming to the opinions of people i've never worked with (and which seem quite whimsical at times), makes a big difference.

### using a sha'd path for the style guide

i disagree. i think the goal is to enforce a common style across all our projects. if the style evolves, the projects should be expected to evolve as well. if that takes some time, `.rubocop_todo.yml` is a better place to indicate "we haven't got around to updating this yet".

as such, i think `.rubocop.yml` should always track the master@HEAD version of our shared guide.

**Comment by mtwentyman** [comment]
As I see it, there's a very real problem with not using versioned includes.  Without it, enforcing new standards happens to projects rather than being accepted by them.  It shouldn't be possible to be in violation of rules that might change on you without an eyes-open step on the part of the project maintainers.  Rubocop upgrades sometimes make for cop name changes too, so both should be upgraded the same way: with intent.  This is a real world issue with upgrades and ruby version differences.  It doesn't respect the fact that one may not have time to fold these new things in right away.  Having to stop and debate variances else allow the majority's opinions to leak into projects feels wrong... and that might lead to the maintainer overriding it in their todo file or more permanently in their configuration.

I'll separate the larger ruby-writing community here and focus just on the people who care to take time to build consensus around a style guide and associated linter.  The normative effects of that larger pool of people coming to regular consensus are for me a very valid foundation, settling on generally agreeable and portable norms.  I think its [prevalent use](https://github.com/search?utf8=%E2%9C%93&q=gem+rubocop+-repo%3Aremore%2Fgemstat&type=Code&ref=searchresults) supports the notion that it is close to if not a defacto standard for ruby linting, even if each project modifies the style to their liking. The configuration exists for the reasons you state, encouraging adoption by allowing people to establish their own rules so that it falls inside the [zone of acceptance](https://yorkesoftware.com/2015/03/22/the-zone-of-acceptance/).  Because its configuration comes along for the ride by default, it has a lot of sway over more broadly recognized standards.  It's not the only option as a linter, and some of its rules annoy me too, but it is widely adopted and has influence on what people consider the standards to be.

That said, I think a narrower "must have" include is probably easier for adoption. FYI the rails .rubocop.yml has only been in place [for about 1/2 a year](https://github.com/rails/rails/commit/7d883b829307944f6d7c273f3915ee7059ee3771); you helped us get started ahead of those slow pokes!  My suspicion is that they _had_ to ease in very selectively to not upset the apple cart.  Maybe that's the right idea for us too.  That would again require a versioned approach IMO.

That was long-winded, but it is in support of this point:  Shared style guides are just difficult to get right.  I appreciate the remarkably fair way it has been done so far especially for a group that isn't shy about their stances and which don't often line up.  As long as the standard we come to promotes better outcomes in our projects through a shared understanding of how we write things so they are easier to read, understand and maintain... :metal:

**Comment by alexdean** [comment]
good discussion, but hasn't been an issue in the past few years, so i'm closing this one out.

**Comment by mtwentyman** [comment]
I agree this issue should be closed because we have agreement on how to make changes, but I just bumped into a cop name change problem with rubocop > 0.67.1 where being able to reference a version of the rules would be helpful so we don't get stuck not being able to update: https://github.com/tedconf/inside/pull/585/commits/1d7b3ecd30bdf1beefd3a08a5c46c03f9a3efd93
